/* Generated By:JavaCC: Do not edit this line. ERConstants.java */
package funciones.lexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ERConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CERO = 1;
  /** RegularExpression Id. */
  int UNO = 2;
  /** RegularExpression Id. */
  int PLUS = 3;
  /** RegularExpression Id. */
  int STAR = 4;
  /** RegularExpression Id. */
  int PIPE = 5;
  /** RegularExpression Id. */
  int PIZQ = 6;
  /** RegularExpression Id. */
  int PDER = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "Expresión Regular incompleta",
    "\"0\"",
    "\"1\"",
    "\"+\"",
    "\"*\"",
    "\"|\"",
    "\"(\"",
    "\")\"",
  };

}
